
# Copyright (C) 2026 Kendall Tauser
#
# This program is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation; either version 2 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License along
# with this program; if not, write to the Free Software Foundation, Inc.,
# 51 Franklin Street, Fifth Floor, Boston, MA 02110-1301 USA.

# Get editor completions based on the config schema
"$schema" = "https://starship.rs/config-schema.json"

add_newline = true
scan_timeout = 25 # File scan ms
command_timeout = 350 # Cmd scan ms

format = """
[‚ï≠‚ï¥](white)\\($time\\) ($kubernetes )($aws )($directory )($git_branch ($git_status )($git_metrics ))
[‚ï∞‚ï¥](white)($status)( $sudo )$username[@](bold red)$hostname 
"""

# [palettes.kt]

[time]
disabled = false
format = "[$time](white)"
time_format = "%a %b %d %T"

[username]
disabled = false
format = "[$user]($style)"
style_user = "blue"
style_root = "red"
show_always = true

[hostname]
disabled = false
format = "[$hostname]($style)"
trim_at = "."
style = "green"
ssh_only = false

[status]
disabled = false
format = "[$symbol]($style)"
success_symbol = ""
symbol = "!"
not_found_symbol = "üîç"
not_executable_symbol = "‚ö†Ô∏è"
failure_style = "bold red"

[git_metrics]
disabled = false
format = "([$added]($added_style)/[$deleted]($deleted_style))"
added_style = "green"
deleted_style = "red"

[git_branch]
disabled = false
format = "[$branch]($style)(:$remote_branch)"
style = "yellow"

[git_status]
disabled = false
format = "([$ahead_behind]($style) [($ahead_count/$behind_count)]($style))"
ahead = "‚á°"
behind = "‚á£"
diverged = "‚áï"
style = "red"

[directory]
disabled = false
format = "[$path]($style)"
style = "cyan"
truncation_length = 5
truncate_to_repo = false

[kubernetes]
disabled = true
format = "[$context]($style)"
style = "blue"

[aws]
disabled = false
format = "[$profile/$region( \\[$duration\\])]($style)"
force_display = false
style = "yellow"

[sudo]
disabled = false
format = "[$symbol]($style)"
symbol = "üõ°Ô∏è"
style = "red bold"
